### ISSUE TITLE
Namespace package do not include files and directories outside their submodule, even when they belong to the same namespace

### ISSUE THREAD

**Issue by WillDaSilva** [pypa/flit#489] opened 2021-12-17 04:49 UTC
First I just wanted to say thank you for adding namespace package support. It couldn't have come at a better time for my company and myself, and we're now using it for a large Python project. Unfortunately I cannot share the details of it at this time, so I'll be using a mock example that has the same structure.

-------

We have a Python package `abc`, which has the following file tree:
```
pyproject.toml
abc/
├── core/
│   ├── __init__.py
│   ├── modA.py
│   ├── modB.py
│   ...
└── data/
    ├── dataA.zip
    ├── dataB.zip
    ...
```
Flit packages the above project with the name set to `"abc"`.

Then we have several other Python projects in various other repositories worked on by different teams, all of which are pieces of the `abc` namespace. They all look something like this:
```
pyproject.toml
abc/
├── xyz/
│   ├── __init__.py
│   ├── xyzModA.py
│   ...
└── data/
    ├── xyzDataA.zip
    ...
```
They are packaged by Flit's namespace package feature by setting their names to e.g. `"abc.xyz"`, replacing `xyz` with whatever the name of the submodule for that project is.

After installing these packages, the desired file structure (under `site-packages` or within the wheel file) is:
```
abc/
├── core/
│   ├── __init__.py
│   ├── modA.py
│   ├── modB.py
│   ...
├── xyz/
│   ├── __init__.py
│   ├── xyzModA.py
│   ...
└── data/
    ├── dataA.zip
    ├── dataB.zip
    ├── xyzDataA.zip
    ...
```

Instead, Flit ignores all files and directories that aren't part of the `xyz` submodule, and so we get the following:
```
abc/
├── core/
│   ├── __init__.py
│   ├── modA.py
│   ├── modB.py
│   ...
├── xyz/
│   ├── __init__.py
│   ├── xyzModA.py
│   ...
└── data/
    ├── dataA.zip
    ├── dataB.zip
    ...
```

Note that `abc/data/xyzDataA.zip` is missing.

--------

Would it be possible for Flit to include the entire file tree under `abc/` inside of `abc_xyz-0.1.2-py3-none-any.whl`? As opposed to only including content under `abc/xyz/`. I think this would be desirable behaviour.

While it does open up the opportunity for users to shoot themselves in the foot by accidentally overwriting files that come with the top-level package with which they share a namespace, I think a high level of cooperation is assumed between authors of Python modules that share a namespace, which would largely alleviate this issue.

This change would allow for packages that share namespaces to contribute code, data, tests, config, and whatever else, into shared known locations. Like a plugin system, which I believe was one of the original use-cases for namespace packages.

**Comment by nerdoc** [comment] 2022-12-09 21:08
Same problem here. This is not only true for data, even for code.
I have a data structure with 2 sibling submodules (with python code) within one namespace package:
```
medux   # <-- namespace package
├── common/
│   ├── __init__.py
├── preferences/
│   ├── __init__.py
```

I can tell flit:
```
[tool.flit.module]
name="medux.common"
```
But then `medux.preferences` is left out.

With setuptools this is easily viable (here a setup.cfg)
```
[options]
include_package_data = True
namespace_packages = medux
packages =
    medux.common
    medux.preferences
```
which works reasonably well.

**Comment by takluyver** [comment] 2022-12-10 11:09
So this is kind of by design. Before namespace package support, Flit could package a single top-level module (`foo.py`) or package (`foo/` directory containing `__init__.py`). Now you can put that inside a namespace package rather than at the top level, but the design is still centred around packaging a single module/package, not several.

Flit has always aimed to support a subset of what is possible with Python packaging, so if you need to put more than a single subpackage into a namespace package, I'm afraid you'll need to use another tool. I won't say it will never be supported, but for now I consider it out of scope - sorry.

**Closed by takluyver** 2022-12-10 11:09 UTC

**Comment by nerdoc** [comment] 2022-12-10 13:11
Ok, thanks, to know that makes it easier - in this case split up the packages into separate ones.
