### ISSUE TITLE
Is it possible to install a package located in a git repository?

### ISSUE THREAD

**Issue by wrosko** [pypa/flit#548] opened 2022-05-05 15:32 UTC
Hi, just like this ability in `poetry` does flit have an option for installing git repos? 
https://github.com/python-poetry/poetry/issues/835

Something like `"ssh://git@private.instance.url:12345/organization/mypackage.git"` added to the `pyproject.toml`

**Comment by wrosko** [comment] 2022-05-05 15:54
Ah, duplicate question here https://github.com/pypa/flit/issues/543

**Comment by takluyver** [comment] 2022-05-05 16:50
Closing as a duplicate of #543.

**Closed by takluyver** 2022-05-05 16:50 UTC

**Comment by flying-sheep** [comment] 2022-05-05 16:52
Yeah, the blog post linked there describes the difference between abstract and concrete dependencies.

The way I’d solve it is to set up a “Python simple API” server like this: https://pypicloud.readthedocs.io/en/latest/

Then you can

1. upload packages to it: set up your CI to publish packages there (or publish them manually). You can use the classifier `Private :: Do Not Upload` to prevent accidentally uploading packages to pypi.org instead of your server

   There’s more low tech alternatives, like [PλPI](https://github.com/berislavlopac/plambdapi) or just this in CI, combined with some basic auth proxy:

    ```shell
    python -m- build
    piprepo sync ./dist "s3://${bucket}/${bucket_path}"
    aws ecs update-service --cluster "${cluster_name}" --service "${service_name}" --force-new-deployment
    ```

3. install packages from it or depend on it

   ```shell
   export PIP_EXTRA_INDEX_URL=https://$TOKEN@pypi.yourcompany.com/simple/`
   pip install mypackage # (or some package depending on it)
   ```

Here’s some more in depth stuff: https://medium.com/jobteaser-dev-team/python-packaging-how-do-we-manage-it-at-jobteaser-2bc8d1e9d206

**Comment by flying-sheep** [comment] 2022-05-05 16:54
All this is a bit more complex than just adding a git URL, but will allow you to actually do dependency management. Very worth it.

**Comment by wrosko** [comment] 2022-05-05 16:55
Awesome, thanks so much Phil! Hope you're well :)

**Comment by flying-sheep** [comment] 2022-05-05 16:56
I am, I hope you too!
