### ISSUE TITLE
Backend subprocess exited when trying to invoke get_requires_for_build_wheel

### ISSUE THREAD

**Issue by adamcunnington-mlg** [pypa/flit#610] opened 2022-11-21 22:40 UTC
I have the simplest pyproject.toml file you can imagine:

```python
[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]


[project]
name = "Test"
version = "0.0.1"
```

I am using pip-tools.

```bash
python3.10 -m venv .venv
. .venv/bin/activate
pip install flit pip-tools
pip-compile --no-emit-index-url --quiet --resolver=backtracking pyproject.toml
```

Error:
Backend subprocess exited when trying to invoke get_requires_for_build_wheel
Failed to parse /home/ac/projects/home/temp/pyproject.toml

If I change **build-system** to use setuptools instead of flit, there is no error.
I have no idea what is going on.

**Comment by adamcunnington-mlg** [comment] 2022-11-21 22:49
Wow, I think this was a red herring... somehow - although I don't know how but I now can't reproduce.

My entire issue was actually `requires-python = "3"`. Turns out the value MUST be something like `">3"` otherwise you get this horrific unhandled error that is nigh impossible to debug. I don't know where in the stack this issue comes from.

**Comment by adamcunnington-mlg** [comment] 2022-11-21 22:54
Wow, no, same issue again after fixing this.
Ok, there is something super crazy happening here that is completely non-deterministic.
I run into this error, I start deleting bits from my pyproject.toml and eventually, I stop getting the error and then I tear down my venv and start again and I get the same issue, this time solved by different random cutting of things out.

I have no idea how to debug and don't know if this issue is coming from pip-tools, flit or something more low-level.

**Comment by pradyunsg** [comment] 2022-11-22 01:58
The issue is with pip-compile: https://github.com/jazzband/pip-tools/issues/1583

```sh-session
❯ pip install .
Processing /private/tmp/test
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "/private/tmp/test/.venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/private/tmp/test/.venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/private/tmp/test/.venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/y1/j465wvf92vs938kmgqh63bj80000gn/T/pip-build-env-_48j1h1v/overlay/lib/python3.10/site-packages/flit_core/buildapi.py", line 23, in get_requires_for_build_wheel
          info = read_flit_config(pyproj_toml)
        File "/private/var/folders/y1/j465wvf92vs938kmgqh63bj80000gn/T/pip-build-env-_48j1h1v/overlay/lib/python3.10/site-packages/flit_core/config.py", line 79, in read_flit_config
          return prep_toml_config(d, path)
        File "/private/var/folders/y1/j465wvf92vs938kmgqh63bj80000gn/T/pip-build-env-_48j1h1v/overlay/lib/python3.10/site-packages/flit_core/config.py", line 106, in prep_toml_config
          loaded_cfg = read_pep621_metadata(d['project'], path)
        File "/private/var/folders/y1/j465wvf92vs938kmgqh63bj80000gn/T/pip-build-env-_48j1h1v/overlay/lib/python3.10/site-packages/flit_core/config.py", line 630, in read_pep621_metadata
          raise ConfigError(
      flit_core.config.ConfigError: description must be specified under [project] or listed as a dynamic field
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
❯ pip-compile --no-emit-index-url --resolver=backtracking pyproject.toml                                  
Backend subprocess exited when trying to invoke get_requires_for_build_wheel
Failed to parse /private/tmp/test/pyproject.toml
```

I'll close this, since I don't think there's anything thatt flit can do to help with this since its error is being suppressed.

**Closed by pradyunsg** 2022-11-22 01:58 UTC

**Comment by atugushev** [comment] 2022-11-27 17:43
FTR, the actual tracking issue is here https://github.com/jazzband/pip-tools/issues/1711

**Comment by AntonOfTheWoods** [comment] 2023-11-03 08:49
The slightest error and this will fail... I had `license = { file = "../LICENSE" }` to a file that *does* exist and it fails with this error, when I have `license = { file = "LICENSE" }` to a file that *doesn't* exist, it works fine!!! :-(

**Comment by apaulture** [comment] 2024-03-26 02:58
Interestingly, with pyproject.toml inside a directory (not root), pip-compile will create the `<project.name>.egg-info` directory and compile just fine. Maybe try moving pyproject.toml out of root?

**Comment by moojen** [comment] 2024-07-05 09:19
As @apaulture indicated, excluding pyproject.toml as an inputfile, can prevent this error. Even though the issue is closed, I experienced it on a fresh install (generated by SAAS pegasus).
