### ISSUE TITLE
flit-core 3.8.0 was uploaded to PyPI without a README

### ISSUE THREAD

**Issue by gotmax23** [pypa/flit#617] opened 2022-12-20 17:14 UTC
![image](https://user-images.githubusercontent.com/9920591/208725604-919580c1-29fc-4f68-8afc-46b8a69b19fd.png)

``` console
$ curl https://files.pythonhosted.org/packages/source/f/flit_core/flit_core-3.7.1.tar.gz | tar tz | rg 'flit_core-3.7.1/README.rst'
flit_core-3.7.1/README.rst
$ curl https://files.pythonhosted.org/packages/source/f/flit_core/flit_core-3.8.0.tar.gz | tar tz | rg 'flit_core-3.8.0/README.rst'
(nothing)
```

**Comment by takluyver** [comment] 2022-12-20 17:43
Duplicate of #612 :wink:

**Closed by takluyver** 2022-12-20 17:43 UTC

**Comment by gotmax23** [comment] 2022-12-20 19:57
Doh, I should've checked first. Thanks!
